name: UGATIT
dependencies:
  - python=3.5
  - matplotlib
  - numpy
  - pip
  - pip:
    - opencv-python
    - Pillow
#    - tensorflow==1.14.0 # CPU support
    - tensorflow-gpu==1.14.0
    - imutils
    - Flask